"use strict";

chrome.runtime.onInstalled.addListener(() => {
  console.info("[Arena Chat Exporter] Service worker ready.");
});

function downloadFile(message) {
  return new Promise((resolve, reject) => {
    if (!message.url || typeof message.url !== "string" || !message.url.startsWith("data:")) {
      reject(new Error("Download URL must be a data URI generated by the content script."));
      return;
    }

    chrome.downloads.download(
      {
        url: message.url,
        filename: message.filename,
        saveAs: message.saveAs !== false,
        conflictAction: "uniquify"
      },
      (downloadId) => {
        const lastError = chrome.runtime.lastError;
        if (lastError) {
          reject(new Error(lastError.message));
          return;
        }

        resolve(downloadId);
      }
    );
  });
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (!message || typeof message.type !== "string") {
    return false;
  }

  if (message.type === "ARENA_EXPORTER_PING") {
    sendResponse({ ok: true, phase: "ready" });
    return false;
  }

  if (message.type === "ARENA_EXPORTER_DOWNLOAD") {
    downloadFile(message)
      .then((downloadId) => {
        sendResponse({ ok: true, downloadId });
      })
      .catch((error) => {
        sendResponse({
          ok: false,
          error: error instanceof Error ? error.message : String(error)
        });
      });

    return true;
  }

  return false;
});
